#!/bin/bash
# ##########################################
# build the image
# ##########################################
# Now we call docker build and pass on all
# the choices as build-arg to the Dockerfile
# where they will be interpreted
# ##########################################
# Reads username that the user would like
read -p "Enter your username: " USER
# Reads in password for new user (non-root user)
read -s -p "Enter your password (this will be for both the created user and the root user): " PASS
XKALI_PKG=default

# You can use other desktop environments, although some don't work due to drawing issues
# Valid choices: e17, gnome, i3, i3-gaps, kde, live, lxde, mate, xfce
# i3, i3-gaps and gnome don't render well

# Create docker subnet on 10.1.0.0/24 subnet
docker network create --subnet=10.1.0.0/24 kali-network

docker build \
        -t kali-linux \
        --build-arg DESKTOP_ENVIRONMENT=xfce \
        --build-arg REMOTE_ACCESS=rdp \
        --build-arg KALI_PACKAGE=$XKALI_PKG \
        --build-arg RDP_PORT=3389 \
        --build-arg SSH_PORT=22 \
        --build-arg USER=$USER \
        --build-arg PASS=$PASS \
        .

echo "Your image and container have been built. It will now be started"
docker-compose up -d
