version: "3"

services:
  kali-linux:
    image: kali-linux
    container_name: kali-linux
    hostname: kali
    ports:
      - "3389:3389"
      - "22:22"
    tty: true
    volumes:
      - /home/mdube-manjaro/Desktop/Kali:/home/mdube/Desktop
      - /home/mdube-manjaro/development:/home/mdube/development
    # persistent firefox folder, this is to ensure that your browser settings stay the same when you stop/start the container
      - /home/mdube-manjaro/Desktop/Kali/browser:/home/mdube/.mozilla/firefox
    privileged: True
    devices:
      - /dev/net/tun
    # Openvpn does not like ipv6 in docker, you have to disable this or openvpn won't work
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    # Set default IP, so you don't have to think about it
    networks:
      kali-network:
        ipv4_address: 10.1.0.2

networks:
  kali-network:
    external: true
