version: "3"

services:
  kali-linux:
    image: kali-linux
    container_name: kali-linux
    hostname: kali
    tty: true
    volumes:
      - /home/mark/Desktop/Kali/CTF:/root/CTF
      - /home/mark/Desktop/Kali/home:/root/Desktop
      - /home/mark/.ssh:/root/.ssh
      - /home/mark/Desktop/Kali/home/.zsh_history:/root/.zsh_history
      - /home/mark/development:/root/development
      - /home/mark/Desktop/Kali/opt:/opt
      # persistent firefox folder, this is to ensure that your browser settings stay the same when you stop/start the container
      - /home/mdube-manjaro/Desktop/Kali/browser:/root/.mozilla/firefox
    privileged: True
    # Openvpn does not like ipv6 in docker, you have to disable this or openvpn won't work
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    # Set default IP, so you don't have to think about it
    networks:
      kali-network:
        ipv4_address: 10.1.0.2
    # network_mode: host

networks:
  kali-network:
    external: true
